import "server-only";

import { MarketStatus, Prisma } from "@prisma/client";
import { prisma } from "@orakly/database";
import type { LiveMarketCardDto, LiveMarketsSort } from "@/shared/contracts/live-markets";
import { mapRowsToEnrichedFeedDto } from "./market-feed-enrichment";

export type { LiveMarketCardDto, LiveMarketsSort };

const feedSelect = {
  id: true,
  slug: true,
  title: true,
  volumeTotalUsd: true,
  liquidityUsd: true,
  yesPrice: true,
  closesAt: true,
  status: true,
  category: { select: { name: true } },
  createdAt: true,
  volume24hUsd: true,
  trendingScore: true,
  cryptoSignalId: true,
  autoGenerated: true,
  onChainAddress: true,
  chainId: true,
  creatorAddress: true,
  resolutionSource: true,
  resolvedAt: true,
  narrative: true,
  momentum: true,
  creatorRewardPercent: true,
} satisfies Prisma.MarketSelect;

function parseSort(raw: string | null | undefined): LiveMarketsSort {
  if (raw === "volume" || raw === "newest" || raw === "ending" || raw === "trending") {
    return raw;
  }
  return "trending";
}

export async function getLiveMarkets(input: {
  sort?: string | null;
  status?: string | null;
  limit?: number;
}): Promise<LiveMarketCardDto[]> {
  const sort = parseSort(input.sort);
  const take = Math.min(Math.max(input.limit ?? 6, 1), 24);
  const statusRaw = (input.status ?? "OPEN").toUpperCase();
  const status =
    statusRaw === "RESOLVED"
      ? MarketStatus.RESOLVED
      : statusRaw === "CLOSED" || statusRaw === "DRAFT"
        ? MarketStatus.CLOSED
        : MarketStatus.OPEN;

  const now = new Date();
  const where: Prisma.MarketWhereInput =
    sort === "ending"
      ? {
          status: MarketStatus.OPEN,
          closesAt: { gt: now },
        }
      : { status };

  let orderBy: Prisma.MarketOrderByWithRelationInput[];
  switch (sort) {
    case "volume":
      orderBy = [{ volume24hUsd: "desc" }, { volumeTotalUsd: "desc" }];
      break;
    case "newest":
      orderBy = [{ createdAt: "desc" }];
      break;
    case "ending":
      orderBy = [{ closesAt: "asc" }];
      break;
    case "trending":
    default:
      orderBy = [{ trendingScore: "desc" }, { volume24hUsd: "desc" }];
      break;
  }

  const rows = await prisma.market.findMany({
    where,
    orderBy,
    take,
    select: feedSelect,
  });

  const enriched = await mapRowsToEnrichedFeedDto(rows);
  const ids = enriched.map((m) => m.backendMarketId ?? m.id).filter(Boolean);

  const participantByMarket = new Map<string, number>();
  if (ids.length > 0) {
    try {
      const counts = await prisma.$queryRaw<
        Array<{ marketId: string; participants: bigint }>
      >(Prisma.sql`
        SELECT t."marketId" AS "marketId",
          COUNT(DISTINCT wallet)::bigint AS participants
        FROM (
          SELECT t."marketId", LOWER(COALESCE(b."walletAddress", '')) AS wallet
          FROM "Trade" t
          INNER JOIN "User" b ON b.id = t."buyerId"
          WHERE t."marketId" IN (${Prisma.join(ids)})
          UNION ALL
          SELECT t."marketId", LOWER(COALESCE(s."walletAddress", '')) AS wallet
          FROM "Trade" t
          INNER JOIN "User" s ON s.id = t."sellerId"
          WHERE t."marketId" IN (${Prisma.join(ids)})
        ) t
        WHERE wallet <> ''
        GROUP BY t."marketId"
      `);
      for (const row of counts) {
        participantByMarket.set(row.marketId, Number(row.participants));
      }
    } catch {
      /* optional enrichment — cards still render */
    }
  }

  return enriched.map((m) => ({
    ...m,
    participants: participantByMarket.get(m.backendMarketId ?? m.id) ?? 0,
  }));
}
