/**
 * Scoped markets lists for hub lanes vs full directory (`GET /api/v1/markets`).
 */
import { MarketStatus, Prisma } from "@prisma/client";
import { prisma } from "@orakly/database";
import { getFeaturedMarkets as staticFeaturedMarkets } from "@/features/markets/api/get-featured-markets";
import { prismaMarketToFeedDto } from "./market-feed-mapper";

/** Hub feeds must not swallow DB failures as an empty list (misleading “syncing” UI). */
export class MarketsFeedDatabaseError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "MarketsFeedDatabaseError";
  }
}

export type MarketsFeedScope = "hub" | "full";

/** “Trending now” chip lane — `/dapp` hub. */
export type MarketsTrendingLane = "volume" | "activity" | "new" | "hot";

/** “Markets” chip lane — `/dapp` hub + directory-style filtering. */
export type MarketsListLaneFilter =
  | "all"
  | "trending"
  | "new"
  | "cross_hot"
  | "breaking"
  | "top_gainers"
  | "meme"
  | "rug_watch"
  | "ending_soon"
  | "high_volume"
  | "moonshots";

export type MarketsFeedLane =
  | "trending"
  | "list"
  | "alpha"
  | /** Explorer default — large unpaged slice */
    "directory";

const feedSelect = {
  id: true,
  slug: true,
  title: true,
  volumeTotalUsd: true,
  liquidityUsd: true,
  yesPrice: true,
  closesAt: true,
  status: true,
  category: { select: { name: true } },
  createdAt: true,
  volume24hUsd: true,
  trendingScore: true,
  cryptoSignalId: true,
  autoGenerated: true,
} satisfies Prisma.MarketSelect;

function clampTake(scope: MarketsFeedScope, lane: MarketsFeedLane, n: number) {
  if (lane === "directory") {
    return Math.min(200, Math.max(1, n));
  }
  if (scope === "full") {
    return Math.min(120, Math.max(1, n));
  }
  return Math.min(48, Math.max(1, n));
}

export async function getMarketsFeedScoped(input: {
  scope: MarketsFeedScope;
  lane: MarketsFeedLane;
  trendingBy?: MarketsTrendingLane;
  listFilter?: MarketsListLaneFilter;
  take: number;
  /**
   * When `false` and the DB returns zero rows, returns `[]` instead of static featured markets
   * (hub Alpha Drops empty state).
   */
  staticFallback?: boolean;
}) {
  const take = clampTake(input.scope, input.lane, input.take);
  const now = new Date();

  const baseWhere: Prisma.MarketWhereInput = {
    status: MarketStatus.OPEN,
  };

  let where: Prisma.MarketWhereInput = { ...baseWhere };
  let orderBy: Prisma.MarketOrderByWithRelationInput[] = [
    { trendingScore: "desc" },
    { volume24hUsd: "desc" },
  ];

  switch (input.lane) {
    case "trending": {
      const by = input.trendingBy ?? "volume";
      if (by === "volume") {
        orderBy = [{ volumeTotalUsd: "desc" }, { trendingScore: "desc" }];
      } else if (by === "activity") {
        orderBy = [{ volume24hUsd: "desc" }, { trendingScore: "desc" }];
      } else if (by === "new") {
        orderBy = [{ createdAt: "desc" }];
      } else if (by === "hot") {
        /* Distinct from `lane=list&filter=trending`: tie-break on lifetime volume, not 24h. */
        orderBy = [{ trendingScore: "desc" }, { volumeTotalUsd: "desc" }];
      } else {
        orderBy = [{ trendingScore: "desc" }, { volume24hUsd: "desc" }];
      }
      break;
    }
    case "list": {
      const f = input.listFilter ?? "all";
      switch (f) {
        case "all":
          orderBy = [{ trendingScore: "desc" }, { volume24hUsd: "desc" }];
          break;
        case "trending":
          orderBy = [{ trendingScore: "desc" }, { volume24hUsd: "desc" }];
          break;
        case "new":
          orderBy = [{ createdAt: "desc" }];
          break;
        case "cross_hot":
          where = {
            ...baseWhere,
            cryptoSignalId: { not: null },
          };
          orderBy = [
            { externalMomentumScore: "desc" },
            { trendingScore: "desc" },
            { volume24hUsd: "desc" },
          ];
          break;
        case "breaking":
          where = {
            ...baseWhere,
            cryptoSignalId: { not: null },
            signalLastSeenAt: { not: null },
          };
          orderBy = [
            { signalLastSeenAt: "desc" },
            { externalMomentumScore: "desc" },
          ];
          break;
        case "top_gainers":
          orderBy = [{ volume24hUsd: "desc" }, { volumeTotalUsd: "desc" }];
          break;
        case "meme":
          where = {
            ...baseWhere,
            OR: [
              {
                category: {
                  name: { contains: "meme", mode: "insensitive" },
                },
              },
              { title: { contains: "meme", mode: "insensitive" } },
            ],
          };
          orderBy = [{ trendingScore: "desc" }];
          break;
        case "rug_watch":
          where = {
            ...baseWhere,
            OR: [
              { title: { contains: "rug", mode: "insensitive" } },
              { title: { contains: "scam", mode: "insensitive" } },
              { title: { contains: "honeypot", mode: "insensitive" } },
              { title: { contains: "drain", mode: "insensitive" } },
            ],
          };
          orderBy = [{ trendingScore: "desc" }];
          break;
        case "ending_soon":
          where = {
            ...baseWhere,
            closesAt: { gt: now },
          };
          orderBy = [{ closesAt: "asc" }];
          break;
        case "high_volume":
          orderBy = [{ volumeTotalUsd: "desc" }, { trendingScore: "desc" }];
          break;
        case "moonshots":
          orderBy = [{ trendingScore: "desc" }];
          where = {
            ...baseWhere,
            OR: [
              { yesPrice: { lte: 0.12 } },
              { yesPrice: { gte: 0.88 } },
            ],
          };
          break;
        default:
          orderBy = [{ trendingScore: "desc" }];
      }
      break;
    }
    case "alpha":
      where = {
        ...baseWhere,
        OR: [{ cryptoSignalId: { not: null } }, { autoGenerated: true }],
      };
      orderBy = [{ createdAt: "desc" }];
      break;
    case "directory":
      orderBy = [{ trendingScore: "desc" }, { volume24hUsd: "desc" }];
      break;
    default:
      break;
  }

  const useStaticFallback = input.staticFallback !== false;

  try {
    const rows = await prisma.market.findMany({
      where,
      orderBy,
      take,
      select: feedSelect,
    });
    if (rows.length === 0) {
      return useStaticFallback ? staticFeaturedMarkets() : [];
    }
    return rows.map(prismaMarketToFeedDto);
  } catch (e) {
    if (!useStaticFallback) {
      const msg = e instanceof Error ? e.message : String(e);
      throw new MarketsFeedDatabaseError(msg);
    }
    return staticFeaturedMarkets();
  }
}
