import "server-only";

import { MarketStatus, Prisma } from "@prisma/client";
import { prisma } from "@orakly/database";
import { slugToDisplayName } from "@/lib/narrative-slug";
import type {
  MarketsExplorerParams,
  MarketsExplorerResult,
  MarketsExplorerSort,
} from "@/shared/contracts/markets-explorer";
import { buildNarrativeMarketWhere } from "./hub-narrative-match";
import { mapRowsToEnrichedFeedDto } from "./market-feed-enrichment";

const feedSelect = {
  id: true,
  slug: true,
  title: true,
  volumeTotalUsd: true,
  liquidityUsd: true,
  yesPrice: true,
  closesAt: true,
  status: true,
  category: { select: { name: true } },
  createdAt: true,
  volume24hUsd: true,
  trendingScore: true,
  cryptoSignalId: true,
  autoGenerated: true,
  onChainAddress: true,
  chainId: true,
  creatorAddress: true,
  resolutionSource: true,
  resolvedAt: true,
  narrative: true,
  momentum: true,
  creatorRewardPercent: true,
} satisfies Prisma.MarketSelect;

function parseSort(raw: string | null | undefined): MarketsExplorerSort {
  if (
    raw === "volume" ||
    raw === "newest" ||
    raw === "ending" ||
    raw === "discussed" ||
    raw === "trending"
  ) {
    return raw;
  }
  return "trending";
}

function parseStatus(raw: string | null | undefined): MarketStatus | "ALL" | null {
  if (!raw || raw.toLowerCase() === "all") return "ALL";
  const u = raw.trim().toUpperCase();
  if (u === "OPEN") return MarketStatus.OPEN;
  if (u === "RESOLVED") return MarketStatus.RESOLVED;
  if (u === "PAUSED") return MarketStatus.PAUSED;
  if (u === "PENDING" || u === "DRAFT") return MarketStatus.DRAFT;
  if (u === "CLOSED") return MarketStatus.CLOSED;
  return null;
}

function categoryWhere(category: string): Prisma.MarketWhereInput | undefined {
  const c = category.trim().toLowerCase();
  if (!c || c === "all" || c === "all categories") return undefined;

  if (c === "other") {
    return {
      OR: [
        { category: null },
        { category: { name: { equals: "Other", mode: "insensitive" } } },
        { category: { name: { equals: "General", mode: "insensitive" } } },
      ],
    };
  }

  const tokenMap: Record<string, string[]> = {
    meme: ["meme", "memes"],
    defi: ["defi"],
    layer1: ["layer1", "layer 1", "l1"],
    layer2: ["layer2", "layer 2", "l2"],
    ai: ["ai", "artificial"],
  };

  const tokens = tokenMap[c.replace(/\s+/g, "")] ?? [c];
  return {
    OR: tokens.map((t) => ({
      category: { name: { contains: t, mode: "insensitive" as const } },
    })),
  };
}

function narrativeWhere(narrative: string): Prisma.MarketWhereInput {
  const slug = narrative.trim();
  const name = slugToDisplayName(slug);
  return {
    OR: [
      { narrative: { equals: slug, mode: "insensitive" } },
      { narrative: { equals: name, mode: "insensitive" } },
      { narrative: { contains: slug, mode: "insensitive" } },
      buildNarrativeMarketWhere(name),
    ],
  };
}

function parseDayStart(iso: string): Date | null {
  const d = new Date(iso);
  if (!Number.isFinite(d.getTime())) return null;
  d.setUTCHours(0, 0, 0, 0);
  return d;
}

function parseDayEnd(iso: string): Date | null {
  const d = new Date(iso);
  if (!Number.isFinite(d.getTime())) return null;
  d.setUTCHours(23, 59, 59, 999);
  return d;
}

/** Probability URL values may be 0–100 (%) or 0–1 fractions. */
function toProbFraction(raw: number, fallback: number): number {
  if (!Number.isFinite(raw)) return fallback;
  if (raw > 1) return Math.min(1, Math.max(0, raw / 100));
  return Math.min(1, Math.max(0, raw));
}

function buildWhere(input: MarketsExplorerParams): Prisma.MarketWhereInput {
  const and: Prisma.MarketWhereInput[] = [];

  const status = parseStatus(input.status);
  if (status && status !== "ALL") {
    and.push({ status });
  }

  const q = input.q?.trim();
  if (q) {
    and.push({
      OR: [
        { title: { contains: q, mode: "insensitive" } },
        { narrative: { contains: q, mode: "insensitive" } },
        { slug: { contains: q, mode: "insensitive" } },
      ],
    });
  }

  const cat = categoryWhere(input.category ?? "");
  if (cat) and.push(cat);

  const narrative = input.narrative?.trim();
  if (narrative && narrative.toLowerCase() !== "all" && narrative !== "All Narratives") {
    and.push(narrativeWhere(narrative));
  }

  const creator = input.creator?.trim();
  if (creator) {
    and.push({ creatorAddress: { contains: creator, mode: "insensitive" } });
  }

  if (input.communityOnly) {
    and.push({
      AND: [
        { creatorAddress: { not: null } },
        { NOT: { creatorAddress: "" } },
      ],
    });
  }

  const from = input.dateFrom ? parseDayStart(input.dateFrom) : null;
  const to = input.dateTo ? parseDayEnd(input.dateTo) : null;
  if (from || to) {
    and.push({
      closesAt: {
        ...(from ? { gte: from } : {}),
        ...(to ? { lte: to } : {}),
      },
    });
  }

  const minVol = input.minVolume;
  const maxVol = input.maxVolume;
  if (
    (minVol != null && Number.isFinite(minVol)) ||
    (maxVol != null && Number.isFinite(maxVol))
  ) {
    and.push({
      volumeTotalUsd: {
        ...(minVol != null && Number.isFinite(minVol) ? { gte: minVol } : {}),
        ...(maxVol != null && Number.isFinite(maxVol) ? { lte: maxVol } : {}),
      },
    });
  }

  const minP =
    input.minProbability != null ? toProbFraction(input.minProbability, 0) : null;
  const maxP =
    input.maxProbability != null ? toProbFraction(input.maxProbability, 1) : null;
  if (minP != null || maxP != null) {
    and.push({
      yesPrice: {
        ...(minP != null ? { gte: minP } : {}),
        ...(maxP != null ? { lte: maxP } : {}),
      },
    });
  }

  const sort = parseSort(input.sort);
  if (sort === "ending") {
    and.push({ status: MarketStatus.OPEN, closesAt: { gt: new Date() } });
  }

  return and.length > 0 ? { AND: and } : {};
}

function buildOrderBy(
  sort: MarketsExplorerSort,
): Prisma.MarketOrderByWithRelationInput[] {
  switch (sort) {
    case "volume":
      return [{ volumeTotalUsd: "desc" }, { volume24hUsd: "desc" }];
    case "newest":
      return [{ createdAt: "desc" }];
    case "ending":
      return [{ closesAt: "asc" }];
    case "discussed":
      return [{ trades: { _count: "desc" } }, { volume24hUsd: "desc" }];
    case "trending":
    default:
      return [{ trendingScore: "desc" }, { volume24hUsd: "desc" }];
  }
}

async function loadParticipantCounts(
  ids: string[],
): Promise<Map<string, number>> {
  const map = new Map<string, number>();
  if (ids.length === 0) return map;

  try {
    const counts = await prisma.$queryRaw<
      Array<{ marketId: string; participants: bigint }>
    >(Prisma.sql`
      SELECT t."marketId" AS "marketId",
        COUNT(DISTINCT wallet)::bigint AS participants
      FROM (
        SELECT t."marketId", LOWER(COALESCE(b."walletAddress", '')) AS wallet
        FROM "Trade" t
        INNER JOIN "User" b ON b.id = t."buyerId"
        WHERE t."marketId" IN (${Prisma.join(ids)})
        UNION ALL
        SELECT t."marketId", LOWER(COALESCE(s."walletAddress", '')) AS wallet
        FROM "Trade" t
        INNER JOIN "User" s ON s.id = t."sellerId"
        WHERE t."marketId" IN (${Prisma.join(ids)})
      ) t
      WHERE wallet <> ''
      GROUP BY t."marketId"
    `);
    for (const row of counts) {
      map.set(row.marketId, Number(row.participants));
    }
  } catch {
    /* optional */
  }
  return map;
}

export async function listMarketsExplorer(
  input: MarketsExplorerParams,
): Promise<MarketsExplorerResult> {
  const page = Math.max(1, Math.floor(input.page ?? 1));
  const limit = Math.min(Math.max(Math.floor(input.limit ?? 20), 1), 100);
  const sort = parseSort(input.sort);
  const where = buildWhere(input);
  const orderBy = buildOrderBy(sort);
  const skip = (page - 1) * limit;

  const [total, rows] = await Promise.all([
    prisma.market.count({ where }),
    prisma.market.findMany({
      where,
      orderBy,
      skip,
      take: limit,
      select: feedSelect,
    }),
  ]);

  const enriched = await mapRowsToEnrichedFeedDto(rows);
  const ids = enriched.map((m) => m.backendMarketId ?? m.id).filter(Boolean);
  const participants = await loadParticipantCounts(ids);

  const markets = enriched.map((m) => ({
    ...m,
    participants: participants.get(m.backendMarketId ?? m.id) ?? 0,
  }));

  const totalPages = Math.max(1, Math.ceil(total / limit));

  return {
    markets,
    total,
    page,
    totalPages,
  };
}

/** True when request should use the paginated explorer API (not live hub / feed lanes). */
export function isMarketsExplorerRequest(sp: URLSearchParams): boolean {
  if (sp.has("page")) return true;
  if (sp.get("sort") === "discussed") return true;
  const explorerKeys = [
    "q",
    "category",
    "creator",
    "dateFrom",
    "dateTo",
    "minVolume",
    "maxVolume",
    "minProbability",
    "maxProbability",
    "community",
  ] as const;
  return explorerKeys.some((k) => {
    const v = sp.get(k)?.trim();
    return Boolean(v);
  });
}

export function parseMarketsExplorerParams(
  sp: URLSearchParams,
): MarketsExplorerParams {
  const num = (key: string): number | undefined => {
    const raw = sp.get(key);
    if (raw == null || raw === "") return undefined;
    const n = Number(raw);
    return Number.isFinite(n) ? n : undefined;
  };

  return {
    q: sp.get("q")?.trim() || undefined,
    category: sp.get("category")?.trim() || undefined,
    status: sp.get("status")?.trim() || undefined,
    narrative: sp.get("narrative")?.trim() || undefined,
    creator: sp.get("creator")?.trim() || undefined,
    dateFrom: sp.get("dateFrom")?.trim() || undefined,
    dateTo: sp.get("dateTo")?.trim() || undefined,
    minVolume: num("minVolume"),
    maxVolume: num("maxVolume"),
    minProbability: num("minProbability"),
    maxProbability: num("maxProbability"),
    communityOnly: sp.get("community") === "1" || sp.get("community") === "true",
    sort: sp.get("sort")?.trim() || "trending",
    page: num("page") ?? 1,
    limit: num("limit") ?? 20,
  };
}
