import "server-only";

import { MarketStatus, Prisma } from "@prisma/client";
import { prisma } from "@orakly/database";
import { slugToDisplayName } from "@/lib/narrative-slug";
import { buildNarrativeMarketWhere } from "./hub-narrative-match";
import {
  mapRowsToEnrichedFeedDto,
  type EnrichedMarketFeedDto,
} from "./market-feed-enrichment";

const feedSelect = {
  id: true,
  slug: true,
  title: true,
  volumeTotalUsd: true,
  liquidityUsd: true,
  yesPrice: true,
  closesAt: true,
  status: true,
  category: { select: { name: true } },
  createdAt: true,
  volume24hUsd: true,
  trendingScore: true,
  cryptoSignalId: true,
  autoGenerated: true,
  onChainAddress: true,
  chainId: true,
  creatorAddress: true,
  resolutionSource: true,
  resolvedAt: true,
  narrative: true,
  momentum: true,
  creatorRewardPercent: true,
} satisfies Prisma.MarketSelect;

export function narrativeMarketWhere(slug: string): Prisma.MarketWhereInput {
  const name = slugToDisplayName(slug);
  return {
    OR: [
      { narrative: { equals: slug, mode: "insensitive" } },
      { narrative: { equals: name, mode: "insensitive" } },
      buildNarrativeMarketWhere(name),
    ],
  };
}

export async function getMarketsByNarrative(
  slug: string,
  take = 20,
): Promise<EnrichedMarketFeedDto[]> {
  const rows = await prisma.market.findMany({
    where: {
      AND: [{ status: MarketStatus.OPEN }, narrativeMarketWhere(slug)],
    },
    orderBy: [{ volume24hUsd: "desc" }, { volumeTotalUsd: "desc" }],
    take,
    select: feedSelect,
  });

  return mapRowsToEnrichedFeedDto(rows);
}

export async function countResolvedMarketsByNarrative(slug: string): Promise<number> {
  return prisma.market.count({
    where: {
      AND: [{ status: MarketStatus.RESOLVED }, narrativeMarketWhere(slug)],
    },
  });
}
