import { prisma } from "@orakly/database";
import {
  MarketStatus,
  MarketSuggestionStatus,
  Prisma,
} from "@prisma/client";
import type { NarrativeScoreRow } from "./narrativeEngine.service.js";

const PUBLISH_TEMPLATES: Record<
  string,
  { title: string; description: string; categorySlug: string; closesDays: number }
> = {
  AI: {
    title: "Will AI tokens outperform memecoins in the next 30 days?",
    description: "AI narrative attention spiked. Relative performance vs memecoins.",
    categorySlug: "crypto-narratives",
    closesDays: 30,
  },
  Memes: {
    title: "Will memecoins regain dominance over DeFi this month?",
    description: "Meme attention cycle heating up vs DeFi flows.",
    categorySlug: "meme-coins",
    closesDays: 30,
  },
  Solana: {
    title: "Will Solana ecosystem TVL grow faster than Base this quarter?",
    description: "Solana narrative momentum vs Base L2 attention.",
    categorySlug: "ecosystems",
    closesDays: 90,
  },
  Base: {
    title: "Will Base chain activity exceed Solana this month?",
    description: "Base L2 narrative surge vs Solana engagement.",
    categorySlug: "ecosystems",
    closesDays: 30,
  },
  DeFi: {
    title: "Will DeFi total volume beat gaming narratives in 30 days?",
    description: "DeFi capital rotation signal vs gaming attention.",
    categorySlug: "crypto-narratives",
    closesDays: 30,
  },
  Gaming: {
    title: "Will gaming narratives outperform RWA this month?",
    description: "GameFi attention vs real-world asset narrative.",
    categorySlug: "market-sentiment",
    closesDays: 30,
  },
  RWA: {
    title: "Will RWA tokenization narratives lead DeFi growth?",
    description: "RWA institutional flow signal vs broader DeFi.",
    categorySlug: "industry-events",
    closesDays: 30,
  },
  ETF: {
    title: "Will ETF flows dominate AI token performance this month?",
    description: "ETF macro narrative vs AI crypto beta.",
    categorySlug: "industry-events",
    closesDays: 30,
  },
};

function slugify(title: string): string {
  const base = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 72);
  return `${base}-${Date.now().toString(36)}`;
}

function envBool(name: string, fallback: boolean): boolean {
  const v = process.env[name]?.trim().toLowerCase();
  if (!v) return fallback;
  return v === "true" || v === "1" || v === "yes";
}

function scoreDeltaPct(current: number, previous: number | null): number {
  if (previous == null || previous <= 0) return 0;
  return ((current - previous) / previous) * 100;
}

/**
 * Rising narratives from external APIs → live OPEN markets linked via MarketSuggestion.
 * Set `NARRATIVE_AUTO_PUBLISH=false` to keep suggestions-only mode.
 */
export async function autoPublishNarrativeMarkets(input: {
  narratives: NarrativeScoreRow[];
  volumeSpikes: string[];
}): Promise<number> {
  if (!envBool("NARRATIVE_AUTO_PUBLISH", true)) return 0;

  const minScore = Number(process.env.NARRATIVE_AUTO_PUBLISH_MIN_SCORE ?? 55);
  const minDelta = Number(process.env.NARRATIVE_AUTO_PUBLISH_MIN_DELTA_PCT ?? 8);
  let published = 0;

  for (const row of input.narratives) {
    const delta = scoreDeltaPct(row.score, row.previousScore);
    const volumeSpike = input.volumeSpikes.includes(row.narrative);
    const hot =
      row.score >= minScore && (delta >= minDelta || volumeSpike || row.trend === "RISING");
    if (!hot) continue;

    const template = PUBLISH_TEMPLATES[row.narrative];
    if (!template) continue;

    const linkedLive = await prisma.market.count({
      where: {
        status: MarketStatus.OPEN,
        marketSuggestion: { narrative: row.narrative },
      },
    });
    if (linkedLive > 0) continue;

    const category = await prisma.category.findFirst({
      where: { slug: template.categorySlug },
    });

    const triggerReason = volumeSpike
      ? `Volume spike · ${row.narrative}`
      : `Attention +${delta.toFixed(1)}% · score ${row.score.toFixed(0)}`;

    await prisma.$transaction(async (tx) => {
      const suggestion = await tx.marketSuggestion.create({
        data: {
          title: template.title,
          description: template.description,
          category: template.categorySlug,
          narrative: row.narrative,
          votesUp: 0,
          votesDown: 0,
          status: MarketSuggestionStatus.APPROVED,
          triggerReason,
        },
      });

      const now = new Date();
      const closesAt = new Date(now.getTime() + template.closesDays * 86_400_000);

      const market = await tx.market.create({
        data: {
          slug: slugify(template.title),
          title: template.title,
          description: template.description,
          categoryId: category?.id ?? null,
          status: MarketStatus.OPEN,
          autoGenerated: true,
          opensAt: now,
          closesAt,
          yesPrice: new Prisma.Decimal(0.5),
          noPrice: new Prisma.Decimal(0.5),
          liquidityUsd: new Prisma.Decimal(2_500),
          volume24hUsd: new Prisma.Decimal(0),
          trendingScore: new Prisma.Decimal(row.score * 10),
          trendingUpdatedAt: now,
          generationMeta: {
            source: "narrative_auto_publish",
            narrative: row.narrative,
            attentionScore: row.score,
            triggerReason,
          },
        },
      });

      await tx.marketSuggestion.update({
        where: { id: suggestion.id },
        data: { marketId: market.id },
      });
    });

    published += 1;
  }

  return published;
}
