import type { AttentionDashboardItem } from "@/shared/contracts/attention-dashboard";

/**
 * Swappable demo desk for Trending Narratives when the attention API has no
 * real rows yet. Replace / delete once production AttentionScore is always warm.
 */
const NOW = Date.now();

function hoursAgo(h: number): string {
  return new Date(NOW - h * 3_600_000).toISOString();
}

export const TRENDING_NARRATIVES_DEMO: readonly AttentionDashboardItem[] = [
  {
    id: "demo-ai",
    narrativeSlug: "ai",
    narrativeName: "AI",
    attentionScore: 78,
    convictionScore: 71,
    momentum: "Growing",
    volume24hUsd: 1_850_000,
    activeMarkets: 5,
    uniqueTraders: 412,
    liquidity: 920_000,
    openInterest: 2_400_000,
    scorePrev24h: 64,
    lastUpdated: hoursAgo(2),
  },
  {
    id: "demo-memes",
    narrativeSlug: "memes",
    narrativeName: "Memes",
    attentionScore: 61,
    convictionScore: 48,
    momentum: "Cooling",
    volume24hUsd: 1_420_000,
    activeMarkets: 4,
    uniqueTraders: 580,
    liquidity: 510_000,
    openInterest: 890_000,
    scorePrev24h: 69,
    lastUpdated: hoursAgo(4),
  },
  {
    id: "demo-ethereum",
    narrativeSlug: "ethereum",
    narrativeName: "Ethereum",
    attentionScore: 66,
    convictionScore: 62,
    momentum: "Growing",
    volume24hUsd: 2_100_000,
    activeMarkets: 6,
    uniqueTraders: 340,
    liquidity: 1_100_000,
    openInterest: 2_800_000,
    scorePrev24h: 58,
    lastUpdated: hoursAgo(6),
  },
  {
    id: "demo-bnb",
    narrativeSlug: "bnb",
    narrativeName: "BNB",
    attentionScore: 67,
    convictionScore: 63,
    momentum: "Growing",
    volume24hUsd: 980_000,
    activeMarkets: 4,
    uniqueTraders: 265,
    liquidity: 740_000,
    openInterest: 1_350_000,
    scorePrev24h: 55,
    lastUpdated: hoursAgo(1),
  },
  {
    id: "demo-base",
    narrativeSlug: "base",
    narrativeName: "Base",
    attentionScore: 59,
    convictionScore: 55,
    momentum: "Growing",
    volume24hUsd: 640_000,
    activeMarkets: 3,
    uniqueTraders: 176,
    liquidity: 420_000,
    openInterest: 710_000,
    scorePrev24h: 50,
    lastUpdated: hoursAgo(8),
  },
  {
    id: "demo-solana",
    narrativeSlug: "solana",
    narrativeName: "Solana",
    attentionScore: 56,
    convictionScore: 52,
    momentum: "Cooling",
    volume24hUsd: 1_150_000,
    activeMarkets: 5,
    uniqueTraders: 290,
    liquidity: 610_000,
    openInterest: 980_000,
    scorePrev24h: 61,
    lastUpdated: hoursAgo(12),
  },
  {
    id: "demo-gaming",
    narrativeSlug: "gaming",
    narrativeName: "Gaming",
    attentionScore: 44,
    convictionScore: 40,
    momentum: "Cooling",
    volume24hUsd: 280_000,
    activeMarkets: 2,
    uniqueTraders: 112,
    liquidity: 210_000,
    openInterest: 320_000,
    scorePrev24h: 49,
    lastUpdated: hoursAgo(18),
  },
  {
    id: "demo-rwa",
    narrativeSlug: "rwa",
    narrativeName: "RWA",
    attentionScore: 48,
    convictionScore: 46,
    momentum: "Growing",
    volume24hUsd: 410_000,
    activeMarkets: 3,
    uniqueTraders: 94,
    liquidity: 280_000,
    openInterest: 390_000,
    scorePrev24h: 41,
    lastUpdated: hoursAgo(3),
  },
  {
    id: "demo-defi",
    narrativeSlug: "defi",
    narrativeName: "DeFi",
    attentionScore: 54,
    convictionScore: 57,
    momentum: "Stable",
    volume24hUsd: 760_000,
    activeMarkets: 4,
    uniqueTraders: 198,
    liquidity: 680_000,
    openInterest: 1_100_000,
    scorePrev24h: 53,
    lastUpdated: hoursAgo(10),
  },
] as const;
