/**
 * Batch-deploy OPEN auto markets missing onChainAddress (viem + DEPLOYER_PRIVATE_KEY).
 *
 * Usage:
 *   DEPLOYER_PRIVATE_KEY=0x… npx tsx scripts/batch-deploy-markets.mts
 *
 * Requires funded wallet with collateral (~$105/market seed+reward) + gas on chain 97.
 */
import { config } from "dotenv";
import { resolve } from "node:path";
import {
  createPublicClient,
  createWalletClient,
  decodeEventLog,
  http,
  maxUint256,
  parseUnits,
  type Address,
  type Abi,
} from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { bscTestnet } from "viem/chains";

config({ path: resolve(process.cwd(), ".env.local") });
config({ path: resolve(process.cwd(), ".env") });
config({ path: resolve(process.cwd(), "../../.env.local") });
config({ path: resolve(process.cwd(), "../../.env") });

const FACTORY = (process.env.NEXT_PUBLIC_FACTORY_ADDRESS ||
  "0x180532197f84701e5e183ccbd2f66ea52982dbb2") as Address;
const COLLATERAL = (process.env.NEXT_PUBLIC_COLLATERAL_ADDRESS ||
  "0xf327c48b8acf444311938bf380a26fddb48bb67d") as Address;
const TREASURY = (process.env.NEXT_PUBLIC_TREASURY_ADDRESS ||
  "0xA5c5814BA8F5a3926513fD78DDb0968711Ebe8D4") as Address;
const UMA = (process.env.NEXT_PUBLIC_UMA_OPTIMISTIC_ORACLE_V3 ||
  "0x911a78b32c66261bff31b01a122b4f1e2df8da51") as Address;
const DECIMALS = Number(process.env.NEXT_PUBLIC_COLLATERAL_DECIMALS || "6");
const RPC =
  process.env.BSC_TESTNET_RPC_URL ||
  process.env.NEXT_PUBLIC_RPC_URL ||
  "https://data-seed-prebsc-1-s1.binance.org:8545";
const LIMIT = Number(process.env.BATCH_DEPLOY_LIMIT || "20");

const marketFactoryAbi = [
  {
    type: "function",
    name: "createMarket",
    stateMutability: "nonpayable",
    inputs: [
      { name: "collateral", type: "address" },
      { name: "treasury", type: "address" },
      { name: "optimisticOracle", type: "address" },
      { name: "feeBps", type: "uint16" },
      { name: "question", type: "string" },
      { name: "resolutionSource", type: "string" },
      { name: "category", type: "uint8" },
      { name: "endTime", type: "uint256" },
      { name: "seedLiquidity", type: "uint256" },
      { name: "assertionReward", type: "uint256" },
      { name: "requiredBond", type: "uint256" },
      { name: "assertionLiveness", type: "uint64" },
    ],
    outputs: [{ name: "market", type: "address" }],
  },
  {
    type: "event",
    name: "MarketCreated",
    inputs: [
      { name: "market", type: "address", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "question", type: "string", indexed: false },
      { name: "endTime", type: "uint256", indexed: false },
      { name: "category", type: "uint8", indexed: false },
      { name: "seedLiquidity", type: "uint256", indexed: false },
      { name: "assertionReward", type: "uint256", indexed: false },
    ],
  },
] as const satisfies Abi;

const erc20Abi = [
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const satisfies Abi;

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

async function main() {
  const pk = process.env.DEPLOYER_PRIVATE_KEY?.trim();
  if (!pk) {
    console.error("Set DEPLOYER_PRIVATE_KEY to batch-deploy.");
    process.exit(1);
  }

  const { prisma } = await import("@orakly/database");
  const account = privateKeyToAccount(pk.startsWith("0x") ? (pk as `0x${string}`) : `0x${pk}`);
  const publicClient = createPublicClient({ chain: bscTestnet, transport: http(RPC) });
  const walletClient = createWalletClient({
    account,
    chain: bscTestnet,
    transport: http(RPC),
  });

  const markets = await prisma.market.findMany({
    where: {
      status: "OPEN",
      onChainAddress: null,
      autoGenerated: true,
    },
    orderBy: [{ trendingScore: "desc" }, { createdAt: "asc" }],
    take: LIMIT,
    include: { category: { select: { slug: true } } },
  });

  console.log(`[deploy] ${markets.length} markets to deploy as ${account.address}`);

  const seedL = parseUnits("100", DECIMALS);
  const rew = parseUnits("5", DECIMALS);
  const bond = parseUnits("1", DECIMALS);
  const pull = seedL + rew;

  const bal = await publicClient.readContract({
    address: COLLATERAL,
    abi: erc20Abi,
    functionName: "balanceOf",
    args: [account.address],
  });
  const need = pull * BigInt(Math.max(1, markets.length));
  if (bal < need) {
    console.warn(
      `[deploy] Warning: collateral balance may be low. have=${bal} need≈${need}`,
    );
  }

  let allowance = await publicClient.readContract({
    address: COLLATERAL,
    abi: erc20Abi,
    functionName: "allowance",
    args: [account.address, FACTORY],
  });
  if (allowance < need) {
    if (allowance > 0n) {
      const reset = await walletClient.writeContract({
        address: COLLATERAL,
        abi: erc20Abi,
        functionName: "approve",
        args: [FACTORY, 0n],
      });
      await publicClient.waitForTransactionReceipt({ hash: reset });
    }
    const approveHash = await walletClient.writeContract({
      address: COLLATERAL,
      abi: erc20Abi,
      functionName: "approve",
      args: [FACTORY, maxUint256],
    });
    await publicClient.waitForTransactionReceipt({ hash: approveHash });
    console.log("[deploy] collateral approved");
  }

  let ok = 0;
  for (const m of markets) {
    const endTime = Math.floor(new Date(m.closesAt).getTime() / 1000);
    const category = 1; // Narrative
    try {
      const hash = await walletClient.writeContract({
        address: FACTORY,
        abi: marketFactoryAbi,
        functionName: "createMarket",
        args: [
          COLLATERAL,
          TREASURY,
          UMA,
          25,
          m.title,
          m.description?.trim() ||
            m.resolutionSource?.trim() ||
            "Resolves per Orakly listing rules.",
          category,
          BigInt(endTime),
          seedL,
          rew,
          bond,
          7200n,
        ],
      });
      const receipt = await publicClient.waitForTransactionReceipt({ hash });
      let marketAddress: Address | null = null;
      for (const log of receipt.logs) {
        if (log.address.toLowerCase() !== FACTORY.toLowerCase()) continue;
        try {
          const decoded = decodeEventLog({
            abi: marketFactoryAbi,
            data: log.data,
            topics: log.topics,
          });
          if (decoded.eventName === "MarketCreated") {
            const args = decoded.args as { market?: Address };
            if (args.market) marketAddress = args.market;
          }
        } catch {
          /* skip */
        }
      }
      if (!marketAddress) {
        console.error(`[deploy] no MarketCreated for ${m.slug} tx=${hash}`);
        continue;
      }
      await prisma.market.update({
        where: { id: m.id },
        data: {
          onChainAddress: marketAddress,
          chainId: 97,
          status: "OPEN",
        },
      });
      ok += 1;
      console.log(`[deploy] OK ${ok}/${markets.length} ${m.slug} → ${marketAddress}`);
      await sleep(1500);
    } catch (e) {
      console.error(`[deploy] FAIL ${m.slug}`, e instanceof Error ? e.message : e);
    }
  }

  const tradeable = await prisma.market.count({
    where: { status: "OPEN", onChainAddress: { not: null } },
  });
  console.log(`[deploy] done. tradeable OPEN+address: ${tradeable}`);
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
