import { config } from "dotenv";
import { resolve } from "node:path";
config({ path: resolve(process.cwd(), ".env.local") });
config({ path: resolve(process.cwd(), "../../packages/database/.env") });

async function main() {
  const { prisma } = await import("@orakly/database");
  const open = await prisma.market.count({ where: { status: "OPEN" } });
  const tradeable = await prisma.market.count({
    where: { status: "OPEN", onChainAddress: { not: null } },
  });
  const need = await prisma.market.findMany({
    where: { status: "OPEN", onChainAddress: null },
    orderBy: [{ trendingScore: "desc" }],
    take: 20,
    select: { id: true, slug: true, title: true, autoGenerated: true },
  });
  const hasDeployer = Boolean(process.env.DEPLOYER_PRIVATE_KEY?.trim());
  console.log(
    JSON.stringify(
      { open, tradeable, needDeploy: need.length, hasDeployer, sample: need.slice(0, 5) },
      null,
      2,
    ),
  );
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
