/**
 * Keep top SHOWCASE_AUTO_OPEN_CAP auto OPEN markets; demote the rest to DRAFT (admin).
 * Usage: npx tsx scripts/enforce-showcase-cap.mts
 */
import { config } from "dotenv";
import { resolve } from "node:path";

config({ path: resolve(process.cwd(), ".env.local") });
config({ path: resolve(process.cwd(), ".env") });
config({ path: resolve(process.cwd(), "../../.env.local") });
config({ path: resolve(process.cwd(), "../../.env") });

async function main() {
  const { prisma } = await import("@orakly/database");
  const { showcaseAutoOpenCap } = await import("@orakly/jobs");
  const cap = showcaseAutoOpenCap();

  const openAuto = await prisma.market.findMany({
    where: { status: "OPEN", autoGenerated: true },
    orderBy: [{ trendingScore: "desc" }, { createdAt: "asc" }],
    select: { id: true, slug: true, onChainAddress: true },
  });

  const keep = openAuto.slice(0, cap);
  const demote = openAuto.slice(cap);

  if (demote.length > 0) {
    await prisma.market.updateMany({
      where: { id: { in: demote.map((m) => m.id) } },
      data: { status: "DRAFT" },
    });
  }

  console.log(
    `[cap] kept OPEN ${keep.length}/${cap}; demoted ${demote.length} to DRAFT`,
  );
  const tradeable = keep.filter((m) => m.onChainAddress).length;
  console.log(`[cap] of kept, ${tradeable} already have onChainAddress`);
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
