/**
 * Client showcase bootstrap:
 * 1) Run crypto ingest + narrative pipeline (API → AttentionScore + markets)
 * 2) Cap auto OPEN at SHOWCASE_AUTO_OPEN_CAP (default 20)
 *
 * Usage (from apps/web, with DATABASE_URL loaded):
 *   npx tsx scripts/showcase-bootstrap.mts
 *
 * Optional: CRYPTO_INGEST_MAX_MARKETS=30 CRYPTO_INGEST_MIN_HOT_SCORE=20
 */
import { config } from "dotenv";
import { resolve } from "node:path";

config({ path: resolve(process.cwd(), ".env.local") });
config({ path: resolve(process.cwd(), ".env") });
config({ path: resolve(process.cwd(), "../../.env.local") });
config({ path: resolve(process.cwd(), "../../.env") });

async function main() {
  const { prisma } = await import("@orakly/database");
  const {
    runCryptoIngestionPipeline,
    runNarrativeUpdatePipeline,
    countAutoOpenMarkets,
    showcaseAutoOpenCap,
  } = await import("@orakly/jobs");

  const cap = showcaseAutoOpenCap();
  const before = await countAutoOpenMarkets();
  console.log(`[showcase] auto OPEN before: ${before} / cap ${cap}`);

  process.env.CRYPTO_INGEST_AUTO_PUBLISH ??= "true";
  process.env.NARRATIVE_AUTO_PUBLISH ??= "true";
  process.env.CRYPTO_INGEST_MAX_MARKETS ??= "30";
  process.env.CRYPTO_INGEST_MIN_HOT_SCORE ??= "25";
  process.env.NARRATIVE_AUTO_PUBLISH_MIN_SCORE ??= "35";

  const idempotencyKey = `showcase-bootstrap:${new Date().toISOString()}`;
  console.log("[showcase] crypto ingest…");
  const crypto = await runCryptoIngestionPipeline({
    idempotencyKey,
    skipDraftCreation: false,
  });
  console.log("[showcase] crypto:", crypto.status, crypto.stats ?? crypto.error);

  console.log("[showcase] narrative pipeline…");
  const narrative = await runNarrativeUpdatePipeline();
  console.log("[showcase] narrative:", narrative);

  const after = await countAutoOpenMarkets();
  const openTagged = await prisma.market.count({
    where: {
      status: "OPEN",
      autoGenerated: true,
      OR: [{ narrative: { not: null } }, { marketSuggestion: { isNot: null } }],
    },
  });
  const withChain = await prisma.market.count({
    where: {
      status: "OPEN",
      onChainAddress: { not: null },
    },
  });

  console.log(`[showcase] auto OPEN after: ${after} / cap ${cap}`);
  console.log(`[showcase] auto OPEN with narrative link: ${openTagged}`);
  console.log(`[showcase] OPEN with onChainAddress: ${withChain}`);
  console.log(
    "[showcase] Next: run batch-deploy-markets.mts with DEPLOYER_PRIVATE_KEY to make them tradeable.",
  );

  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
