export const API_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION: "VALIDATION",
  INTERNAL: "INTERNAL",
  UPSTREAM_ERROR: "UPSTREAM_ERROR",
} as const;
