import { prisma } from "@orakly/database";
import { MarketStatus } from "@prisma/client";

/** Client showcase: first N auto-generated markets list OPEN; rest stay DRAFT for admin. */
export function showcaseAutoOpenCap(): number {
  const raw = process.env.SHOWCASE_AUTO_OPEN_CAP ?? process.env.NARRATIVE_AUTO_PUBLISH_MAX;
  if (!raw) return 20;
  const n = Number.parseInt(raw, 10);
  return Number.isFinite(n) && n > 0 ? n : 20;
}

/** Count auto-generated OPEN markets (showcase inventory). */
export async function countAutoOpenMarkets(): Promise<number> {
  return prisma.market.count({
    where: {
      status: MarketStatus.OPEN,
      autoGenerated: true,
    },
  });
}

export async function remainingAutoOpenSlots(): Promise<number> {
  const cap = showcaseAutoOpenCap();
  const used = await countAutoOpenMarkets();
  return Math.max(0, cap - used);
}

/** Prefer OPEN while under cap; otherwise DRAFT for admin review. */
export async function resolveAutoMarketStatus(
  preferOpen: boolean,
): Promise<"OPEN" | "DRAFT"> {
  if (!preferOpen) return "DRAFT";
  const slots = await remainingAutoOpenSlots();
  return slots > 0 ? "OPEN" : "DRAFT";
}
